POST http://localhost:3000/register/ HTTP/1.1
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST  http://localhost:3000/login/ HTTP/1.1
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###

GET  http://localhost:3000/user/tweets/feed/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


###

GET  http://localhost:3000/user/following/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


###

GET  http://localhost:3000/user/followers/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


###

GET  http://localhost:3000/tweets/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


###
GET  http://localhost:3000/tweets/8/likes/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


###

GET  http://localhost:3000/tweets/2/replies HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw

###

GET  http://localhost:3000/user/tweets/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw



###

POST  http://localhost:3000/user/tweets/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw


{
   "tweet": "The Mornings..."
}


###
DELETE  http://localhost:3000/tweets/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MjIyODg1fQ.S0iXcoDYBtOkmVM5HghCghsJ4D-P-QJqLZhgFPfAcAw
